name = "CamiFITS"
uuid = "e3d38e7e-66c0-4598-81c1-d1e9bcf43bf0"
authors = ["Jook Walraven <69215586+walra356@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
